### ISSUE TITLE
Any chance of getting a Flatpak package?

### ISSUE THREAD

**Issue by kobus-v-schoor** [OpenHantek/OpenHantek6022#170]
**Is your feature request related to a problem? Please describe.**
I think having flatpak as an option for installation would be great. It will allow sandboxing the application and distributing updates directly to the users.

**Describe the solution you'd like**
The software just needs to be packaged using flatpak, instructions here: [Building your first Flatpak](https://docs.flatpak.org/en/latest/first-build.html)

**Describe alternatives you've considered**
Snap is a similar solution but I personally like Flatpak much better. I find it much less problematic to use, and I often times prefer using it for applications which aren't in the official Debian repos yet or that are out of date. For instance, I use the Arduino IDE Flatpak instead of the Debian package

**Additional context**
N/A

**Comment by kobus-v-schoor** [comment]
I'm currently busy trying to see if I can get this working, I'll let you know if I can conjure up something useful

**Comment by kobus-v-schoor** [comment]
I've gotten it to successfully build and run with the following manifest:

```yaml
app-id: org.openhantek.OpenHantek
runtime: org.kde.Platform
runtime-version: "5.15"
sdk: org.kde.Sdk
command: OpenHantek
finish-args:
  - --socket=wayland

modules:
  - name: libusb
    sources:
      - type: archive
        url: https://github.com/libusb/libusb/releases/download/v1.0.24/libusb-1.0.24.tar.bz2
        sha256: 7efd2685f7b327326dcfb85cee426d9b871fd70e22caa15bb68d595ce2a2b12a

  - name: openhantek
    buildsystem: cmake
    sources:
      - type: archive
        url: https://github.com/OpenHantek/OpenHantek6022/archive/refs/tags/3.2.tar.gz
        sha256: 68d8111a0241fa28f6e2b0bd415552d0a0ac496fa7ec2ccd4747f1bbbc8ad985
```

I'll probably be getting my scope tomorrow (I don't have it yet), after which I'll hopefully be able to test the USB access (which is almost certainly not currently working). I'll post any other updates here
